### ISSUE TITLE
parsing errors - java.lang.RuntimeException: Warning: cannot find if for else

### ISSUE THREAD

**Issue by Da5hes** [LPhD/Jess#1]
Hi there,

i am trying to import the code for redis
during the import i see alot of errors like this:

```
Error parsing function bytesToHuman. skipping.
java.lang.RuntimeException: Warning: cannot find if for else
	at parsing.Functions.builder.NestingReconstructor.consolidateBlockStarters(NestingReconstructor.java:171)
	at parsing.Functions.builder.NestingReconstructor.consolidate(NestingReconstructor.java:65)
	at parsing.Functions.builder.FunctionContentBuilder.exitStatement(FunctionContentBuilder.java:687)
	at parsing.Functions.CFunctionParseTreeListener.exitStatement(CFunctionParseTreeListener.java:50)
	at antlr.FunctionParser$StatementContext.exitRule(FunctionParser.java:405)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.exitRule(ParseTreeWalker.java:71)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:54)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at parsing.ANTLRParserDriver.walkTree(ANTLRParserDriver.java:104)
	at parsing.ANTLRParserDriver.parseAndWalkString(ANTLRParserDriver.java:67)
	at parsing.FunctionParser.parseAndWalkString(FunctionParser.java:19)
	at parsing.ModuleFunctionParserInterface.parseFunctionContents(ModuleFunctionParserInterface.java:29)
	at parsing.Modules.CModuleParserTreeListener.enterFunction_def(CModuleParserTreeListener.java:234)
	at antlr.ModuleParser$Function_defContext.enterRule(ModuleParser.java:5310)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:66)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:49)
	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:52)
	at parsing.ANTLRParserDriver.walkTree(ANTLRParserDriver.java:104)
	at parsing.ANTLRParserDriver.parseAndWalkFile(ANTLRParserDriver.java:55)
	at parsing.ModuleParser.parseFile(ModuleParser.java:21)
	at tools.parser.CParserCSVOutput.visitFile(CParserCSVOutput.java:18)
	at fileWalker.OrderedWalker.reportFile(OrderedWalker.java:85)
	at fileWalker.OrderedWalker.walk(OrderedWalker.java:55)
	at fileWalker.OrderedWalker.walk(OrderedWalker.java:50)
	at fileWalker.OrderedWalker.walk(OrderedWalker.java:50)
	at fileWalker.OrderedWalker.walkExistingFileOrDirectory(OrderedWalker.java:30)
	at fileWalker.SourceFileWalker.walk(SourceFileWalker.java:33)
	at joern.plugins.importer.CParserWrapper.walkCodebase(CParserWrapper.java:32)
	at joern.plugins.importer.JoernImporter.parseSourceCode(JoernImporter.java:75)
	at joern.plugins.importer.JoernImporter.execute(JoernImporter.java:43)
	at octopus.api.plugin.PluginExecutor.executePlugin(PluginExecutor.java:36)
	at octopus.server.restServer.handlers.ExecutePluginHandler.executePluginAndRespond(ExecutePluginHandler.java:36)
	at octopus.server.restServer.handlers.ExecutePluginHandler.handle(ExecutePluginHandler.java:20)
	at octopus.server.restServer.OctopusRestServer.lambda$start$0(OctopusRestServer.java:36)
	at spark.RouteImpl$1.handle(RouteImpl.java:61)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:126)
	at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
Error connecting #ifdef REDIS_TEST with variability child: }
Error connecting #ifdef REDIS_TEST with variability child: }
Error connecting #ifdef REDIS_TEST with variability child: }

```

i am used to the original joern messages about skipping incomplete CFG's, but this seems more severe with the trace thrown at me more than a couple of times

also regarding Error connecting #ifdef REDIS_TEST with variability child: }
this seems to originate from parsing this case:

```

...(cut out for sanity)...
#ifdef REDIS_TEST
#include <stdio.h>

#define UNUSED(x) (void)(x)
int crc64Test(int argc, char *argv[]) {
    UNUSED(argc);
    UNUSED(argv);
    printf("e9c6d914c4b8d9ca == %016llx\n",
        (unsigned long long) crc64(0,(unsigned char*)"123456789",9));
    return 0;
}
#endif
```

another failed example:

```

#ifdef HAVE_PROC_SOMAXCONN
FILE *fp = fopen("/proc/sys/net/core/somaxconn","r");
char buf[1024];
if (!fp) return;
if (fgets(buf,sizeof(buf),fp) != NULL) {
        int somaxconn = atoi(buf);
        if (somaxconn > 0 && somaxconn < server.tcp_backlog) {
            serverLog(LL_WARNING,"WARNING: The TCP backlog setting of %d cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of %d.", server.tcp_backlog, somaxconn);
        }
    }
    fclose(fp);
#endif
```

**Comment by LPhD** [comment]
Thanks for your report. Which branch did you use? Does this issue still occur with the latest stable branch?

**Comment by Da5hes** [comment]
Hi, at the time i used the latest dev branch, just tested with latest stable and there are no more stack traces of this kind but still a lot of errors regarding #ifdef statements
such as:

```
Error connecting #ifdef REDIS_TEST with variability child: }
Trying to retrieve node ID for node ast.logical.statements.BlockCloser@3cda0d96, but none is set (type = BlockCloser, location = Path:  , Startline: 19, code = })
```

and i met a new stacktrace error:

```
ERROR c.t.t.g.d.StandardTitanGraph - Error while commiting index mutations for transaction [4] on index: search
com.thinkaurelius.titan.core.TitanException: Could not execute operation due to backend exception
	at com.thinkaurelius.titan.diskstorage.util.BackendOperation.execute(BackendOperation.java:44) ~[titan-core-1.0.0.jar:na]
	at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:120) ~[titan-core-1.0.0.jar:na]
	at com.thinkaurelius.titan.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:101) ~[titan-core-1.0.0.jar:na]
	at .........

Caused by: org.apache.lucene.util.BytesRefHash$MaxBytesLengthExceededException: bytes can be at most 32766 in length; got 129999
	at org.apache.lucene.util.BytesRefHash.add(BytesRefHash.java:284) ~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.TermsHashPerField.add(TermsHashPerField.java:151) ~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]
	at org.apache.lucene.index.DefaultIndexingChain$PerField.invert(DefaultIndexingChain.java:663) ~[lucene-core-4.10.4.jar:4.10.4 1662817 - mike - 2015-02-27 16:38:43]


```

you can find the code i am trying to import at https://github.com/antirez/redis if that will help

**Comment by LPhD** [comment]
Did the import finish? These errors are currently tolerated and should't stop the importing process.

The first error is due to the data structure. A code property graph contains an AST, which has no brackets by design. Sometimes, preprocessor statements are used in a so called "undisziplined" way, where they disrupt the syntax of the C code. In your example, there is a curly bracket annotated with an #ifdef. As there are no curly bracket nodes in the resulting graph, the "} node" cannot be connected to the #ifdef node. This may change in the future, though.

The second error hints to a statement that is too long to be stored in one node, as the content (probably the code) is too long to fit into a byte datastructure. For example, this could be the case for a method declaration that has like 20 parameters with long names. As this is a rare problem (and probably not easy to fix without downsides), it is not planned to adress it in the near future.
